[package]
name = "volatility"
version = "0.1.0"
description = "Created with Anchor"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "volatility"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []

[dependencies]
anchor-lang = "0.25.0"
switchboard-v2 = "0.1.16"
spl-math = { version = "0.1.0", features = [ "no-entrypoint" ] }
